### ISSUE TITLE
not a surpise cant even launch.

### ISSUE THREAD

**Issue by TristanJohnsonpng** [WinterTempIQ/MSGen#4]
all you get is a blank cmd window that does absouloutely nothing. even if you run nignode.js you get a browser that just closes.

**Comment by quickdaffy** [comment]
either your solver isnt working or ur proxies are bad

**Comment by DabbyDude** [comment]
I have the same problem. Do you know how I can fix it?

**Comment by DabbyDude** [comment]
And also do the alts go to alts.txt or to the discord webhook?

**Comment by DabbyDude** [comment]
Also, do I need a combo list for this to work?

**Comment by WinterTempIQ** [comment]
Solver patched, closed.
